package:
  name: "mirp"
  version: "1.0.2"

source:
  path: ../

requirements:
  build:
    - python {{ python }}

  host:
    - python
    - numpy >=1.17
    - scipy >=1.3
    - pandas >=1.0.0
    - pydicom >=1.3.0
    - pywavelets >=1.0.0
    - scikit-image >=0.15.0
    - SimpleITK >=1.2.0
    - itk>=5.1.0

  run:
    - python
    - numpy >=1.17
    - scipy >=1.3
    - pandas >=1.0.0
    - pydicom >=1.3.0
    - pywavelets >=1.0.0
    - scikit-image >=0.15.0
    - SimpleITK >=1.2.0
    - itk>=5.1.0

about:
  home: https://github.com/oncoray/mirp
  license: EUPL1.2
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Medical Image Radiomics Processor
  doc_url: https://github.com/oncoray/mirp
